language: perl
perl:
   - 5.19
   - 5.18
   - 5.16
   - 5.14
   - 5.12
   - 5.10

before_install:
#   - sudo apt-get install -qq libssl-dev
   - "perl -ane '$F[0] eq \"author\" || next; s/\\s*;.*$//; m/^\\s*author\\s*=\\s*(.*?)\\s+<?(\\S+?)>?$/; system(qw(echo git config --global user.email), $2); system(qw(echo git config --global user.name), $1);' dist.ini"
#   - cpanm --quiet --notest --skip-satisfied Dist::Zilla::Plugin::MakeMaker::Awesome

install:
  #   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  #   - "dzil authordeps | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied"
  #   - "dzil listdeps   | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied"

script:
  #   - dzil smoke --release --author
  - perl Build.PL; ./Build test
# branches:
# only:
# - master

notifications:
  recipients:
    - you@example.com
  email:
    on_success: change
    on_failure: always

#env:
