# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Dancer::App::Base::HTML5Bootstrap"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template_toolkit:
    start_tag: '[%'
    end_tag:   '%]'
    COMPILE_DIR: 'cache/templates'
    COMPILE_EXT: '.ttc'
    INCLUDE_DIR: 'views:views/layouts'

session: 'YAML'

assets:
  usecdn: 1

plugins:
  Auth::Extensible:
    login_page: '/signin'
    logout_page: '/signout'
    denied_page: '/signin_bad'
    user_home_page: '/account'
    no_default_pages: true
    exit_page: '/signout'
    realms:
      users:
        provider: "Config"
        users:
          - user: user@example.com
            pass: password
            roles:
          - user: admin@example.com
            pass: '{SSHA}+2u1HpOU7ak6iBR6JlpICpAUvSpA/zBM'
            roles:
              - Admin

  CDN:
    base: "/cdn/"
    plugins:
      - "CSS"
      - "CSS::Minifier::XS"

  DebugToolbar:
    enable: 0
    show:
      databases: 1
      routes: 1
      data: 1
      templates: 1

plack_middlewares:
  -
    - Debug
    - panels
    -
      - Parameters
      - Dancer::Version
      - Dancer::Settings
      - Memory
    - Deflater
    - GeoIP
    - ConditionalGET
    - ETag
